### ISSUE TITLE
cant run  dataloader.py

### ISSUE THREAD

**Issue by PurvaChiniya** [HolmesShuan/OISR-PyTorch#6]
I am facing an implementation error in import _DataLoaderIter from torch.utils.data.dataloader  in dataloader.py 
Im using pytorch 1.4.0 and python 3.7
I tried to change _DataLoaderIter to DataLoaderIter. Even that doesn't work.
I tried many ways to debug the error. However, I get the error: 

ImportError                               Traceback (most recent call last)
<ipython-input-17-1a6f3e108a33> in <module>()
      4 from torch._C import _set_worker_signal_handlers, _set_worker_pids,     _remove_worker_pids, _error_if_any_worker_fails
      5 from torch.utils.data.dataloader import DataLoader
----> 6 from torch.utils.data.dataloader import DataLoaderIter

ImportError: cannot import name 'DataLoaderIter'

**Comment by HolmesShuan** [comment]
Thanks for your interest. Please refer to our dependency: **PyTorch==0.4.1**
If you really want to use 1.4.0, I recommend [EDSR](https://github.com/thstkdgus35/EDSR-PyTorch), since they have updated their codes to support 1.2.0. 
[IMDN](https://github.com/Zheng222/IMDN) is another option, they rewrite the dataloader module to utilize the standard PyTorch dataloader.

**Comment by PurvaChiniya** [comment]
Thanks it works now.
