### ISSUE TITLE
About n_feats=?

### ISSUE THREAD

**Issue by ttt-ong** [HolmesShuan/OISR-PyTorch#7]
(NTIRE2019)In  train.sh the n_feats=64, when I use  pre_trained params the n_feats=512, why?

**Comment by HolmesShuan** [comment]
Thanks for pointing out the mistake. I have checked the [`train.sh`](https://github.com/HolmesShuan/OISR-PyTorch/blob/master/NTIRE2019/OISR/src/train.sh) in NTIRE2019 folder. It seems that `n_feats=512`. Could you please further specify your question?

FYI.

If you are interested in Real-SR, I personally think [HBPN](https://github.com/yyknight/NTIRE2019_EDRN) is a good start. We also attend AIM2020 Real-SR challenge. The solution can be found [here](https://github.com/HolmesShuan/AIM2020-Real-Super-Resolution).

For NTIRE2019, we intuitively set `n_feats` as 512 since we thought larger channel numbers would lead to higher performance. In our paper, we use `n_feats=256` to keep the model size and MACs comparable among other works.

The training script is as follow (here we use RK3 on DIV2K as an example):
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --model OISR-RK3 --scale 2 --reset --save OISR-RK3-x2 --reset --ext bin --n_GPUs 4 --epochs 700 --chop --n_resblocks 22 --n_feats 256 --decay 200-400-600 
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --model OISR-RK3 --scale 3 --reset --save OISR-RK3-x3 --reset --ext bin --n_GPUs 4 --epochs 700 --chop --n_resblocks 22 --n_feats 256 --decay 200-400-600 --pre_train ../experiment/OISR-RK3-x2/model/model_best.pt
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --model OISR-RK3 --scale 4 --reset --save OISR-RK3-x4 --reset --ext bin --n_GPUs 4 --epochs 700 --chop --n_resblocks 22 --n_feats 256 --decay 200-400-600 --pre_train ../experiment/OISR-RK3-x3/model/model_best.pt
```
