### ISSUE TITLE
about the log.txt

### ISSUE THREAD

**Issue by songyonger** [HolmesShuan/OISR-PyTorch#8]
In NTIRE2019/OISR/experiment/log.txt，a record 1600/15960 , could you tell me how to get the 15960 please？

**Comment by HolmesShuan** [comment]
We conduct random crop on the original NTIRE RealSR training dataset. Since this Repository was created two years ago, the specific setting was missing. Sorry for any inconvenience. Please refer to the [answer to another issue](https://github.com/HolmesShuan/OISR-PyTorch/issues/7#issuecomment-767949021).

**Comment by songyonger** [comment]
thanks
